language: node_js
node_js:
  - '12'
sudo: false

cache:
  directories:
    - node_modules
    - yarn

jobs:
  include:
    - stage: test
      script:
        - echo 'Deploy!!'
        - echo 'Installing Deps!'
        - yarn
    #        - echo 'Testing!'
    #        - yarn test:prod
    - stage: deploy
      script:
        #        - npm install -g firebase-tools
        - yarn build
        - bash ./.travis-deploy.sh
#        - firebase deploy --token "$FIREBASE_TOKEN"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master
